修改编译中的tag的获取

diff --git a/.github/workflows/win_build.yml b/.github/workflows/win_build.yml
--- a/.github/workflows/win_build.yml
+++ b/.github/workflows/win_build.yml
@@ -46,6 +46,31 @@ jobs:
           git config --global core.autocrlf input
           # npx update-browserslist-db@latest
 
+      - name: Get tag version
+        run: |
+          # 如果是手动触发 (workflow_dispatch)
+          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
+            # 获取所有 Tag（确保包含远程 Tag）
+            git fetch --tags
+            # 按版本号排序获取最新 Tag（兼容语义化版本）
+            LATEST_TAG=$(git tag --sort=-v:refname | head -n 1 || echo "nightly")
+
+           
+          else
+           # 原有逻辑：从推送的 Tag 中提取版本号
+           TAG_NAME="${GITHUB_REF##*/}"
+         
+          fi
+
+          # 处理无 Tag 的情况（可选：报错或默认值）
+          if [ -z "$VERSION" ]; then
+            echo "::error::No valid tag found!"
+            VERSION="0.0.0"
+          fi
+
+          # 将信息写入环境变量
+          echo "TAG_NAME=$LATEST_TAG" >> $GITHUB_ENV
+
       - name: Yarn install windows
         if: matrix.os == 'windows-latest'
         run: |
